# This is a basic workflow to help you get started with Actions

name: GitHubPages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Install and Build Angular
        working-directory: src/mlservicewrapper-host-http-ui/
        run: |
          npm install
          npm run build -- --prod --out-dir ../dist/ --base-href /ml-service-wrapper-host-http-ui/

      - name: Install and Build Inject
        working-directory: src/inject/
        run: |
          npm install
          npm run build -- --out-dir ../dist/inject

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: src/dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

 #     - name: Angular Deploy gh-pages Actions
 #       uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
 #       with:
 #         angular_project_dir: src/mlservicewrapper-host-http-ui/
 #         github_access_token: ${{ secrets.ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
 #         build_configuration: production # The build environment for the app. please look configurations in your angular.json
 #         base_href: /ml-service-wrapper-host-http-ui/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
 #         deploy_branch: gh-pages # The branch the action should deploy to.
 #         angular_dist_build_folder: src/mlservicewrapper-host-http-ui/dist/mlservicewrapper-host-http-ui
